### PR TITLE
Port SUclass theme to Ginkgo

### PR DESCRIPTION
**Pull request by caesar2164**
@stvstnfrd

### CODE REVIEW

**Comment by caesar2164** [comment]
Symlink all static templates, unless Suclass needs to modify.

**Comment by caesar2164** [comment]
Symlink `redirect_to_tos_and_honor.html` and `print_document_button.html`

**Comment by caesar2164** [comment]
Symlink `quad.jpg`

**Comment by caesar2164** [comment]
rename header images to something more meaningful

**Comment by caesar2164** [comment]
Remove colors.scss comments

**Comment by caesar2164** [comment]
symlink maintenance page

**Review by stvstnfrd — APPROVED** [review]
+1 to squash and merge

**Pull request merged**
