### PR TITLE
Change account activation message on Dashboard

### PR DESCRIPTION
**Pull request by tanyaxp**
Change account activation message on Lagunita Dashboard to remove
account activation text. This improves the user experience for auto
enrolled participants.

### CODE REVIEW

**Comment by tanyaxp** [comment]
@stvstnfrd , @caesar2164 Could you please take a look at this. Thanks!

**Comment by stvstnfrd** [comment]
@tanyaxp Mind attaching a screenshot of the new message/UI?

**Comment by stvstnfrd** [comment]
Also, it looks like this branch is outdated?

> This branch is out-of-date with the base branch

You might try fetching `origin` and then rebasing your branch over `origin/master`.

**Review by stvstnfrd — DISMISSED** [review]

**Review by caesar2164 — DISMISSED** [review]

**Comment by tanyaxp** [comment]
@stvstnfrd Could please review the new changes.
fixed_account_notification

**Review by stvstnfrd — DISMISSED** [review]

**Review by caesar2164 — DISMISSED** [review]

**Comment by stvstnfrd** [comment]
@tanyaxp Mind squashing these two commits and then we'll merge?

**Comment by tanyaxp** [comment]
@stvstnfrd I have squashed the 2 commits. Thanks!

**Review by stvstnfrd — APPROVED** [review]

**Review by caesar2164 — APPROVED** [review]

**Pull request merged**
