### PR TITLE
Fixes width of course header

### PR DESCRIPTION
**Pull request by caesar2164**
allows shopping cart button to go right next course header

@stvstnfrd

### CODE REVIEW

**Comment by caesar2164** [comment]
Before:
screen shot 2018-03-13 at 1 08 01 pm


After:
screen shot 2018-03-13 at 1 11 11 pm

**Comment by stvstnfrd** [comment]
@caesar2164 Do you have screenshots for the text-clipping?

**Comment by caesar2164** [comment]
Before with a long name:
screen shot 2018-03-13 at 2 45 27 pm


After with long course name:
screen shot 2018-03-13 at 2 34 49 pm

**Review by stvstnfrd — APPROVED** [review]
+1

**Pull request merged**
