### PR TITLE
Change HONOR links to ids on TOS page

### PR DESCRIPTION
**Pull request by caesar2164**
@stvstnfrd, settings don't seem to do the right thing, so here's a commit to do it in theme.

### CODE REVIEW

**Comment by stvstnfrd** [comment]
@caesar2164 What settings don't do the right thing?

We've been burnt by hardcoding (even parts of) marketing links, so I'm fairly opposed to reverting to that approach..

**Comment by caesar2164** [comment]
So, I can't seem to be able to define `HONOR` key as `tos#honor` in `MKTG_URL_LINK_MAP`.

**Comment by caesar2164** [comment]
Also, I'm just hardcoding the thing we're hardcoding already in `tos.html`, @stvstnfrd

**Comment by caesar2164** [comment]
Ok @stvstnfrd, now there is no hardcoding at all. The same variable that's used to define the id in the `tos.html` template is also used to define the redirect. The code change in `honor.html` makes complete sense as well, because it clearly shows that the honor page is being redirected to `tos` page at the preset `honor` id.

This also doesn't affect platform or tests at all because the honor template exists like normal.

**Comment by caesar2164** [comment]
New plan: redirect both `tos` and `honor` to `tos_and_honor`.

**Review by stvstnfrd — CHANGES_REQUESTED** [review]
At this point, it looks like `tos.html` and `honor.html` are pretty much the same page, save the title. Let's not maintain two nearly identical pages. How about this...

```sh
vi honor.html
# Update the page title and `h2` to be "Redirecting to Terms of Service and Honor Code..."
git mv honor.html redirect_to_tos_and_honor.html
ln -s redirect_to_tos_and_honor.html honor.html
ln -s redirect_to_tos_and_honor.html tos.html
```

By symlinking, not only do we only need to maintain one actual source file, but it's obvious from just a `ls -l` that the `tos` and `honor` pages are really just redirects; you don't even have to examine the source!

**Pull request merged**
